### ISSUE TITLE
GLSurfaceView 放在布局文件里空指针

### ISSUE THREAD

**Issue by yy182038** [qiniudemo/qiniu-live-android#2]
log:
java.lang.NullPointerException
      at android.opengl.GLSurfaceView.surfaceCreated(GLSurfaceView.java:523)
      at android.view.SurfaceView.updateWindow(SurfaceView.java:573)
      at android.view.SurfaceView.access$000(SurfaceView.java:86)
      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:175)
      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1910)
      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
      at android.view.Choreographer.doCallbacks(Choreographer.java:574)
      at android.view.Choreographer.doFrame(Choreographer.java:544)
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
      at android.os.Handler.handleCallback(Handler.java:733)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:136)
      at android.app.ActivityThread.main(ActivityThread.java:5052)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
      at dalvik.system.NativeStart.main(Native Method)
和demo的写法一样一样的...请问怎么解决呢

**Comment by MistyL** [comment]
使用前有获取GLSurfaceView对象吗？
